### ISSUE TITLE
SchedulesDirect now producing +1/+24 channel data

### ISSUE THREAD

**Issue by MikeB2013** [PBrady43/Channel-Editor#1]
Just a heads up in case your matching algo needs tweaking:
SD are now internally generating +1 and +24 channel data, where their supplier does not have it.

Format in tv_grab_sd_json output is :
`</channel>
  <channel id="3099098">
    <display-name>SD-True Crime +1</display-name>
    <display-name>SD-TRUECRIMEP1</display-name>
    <display-name>152</display-name>
    <icon height="270" src="https://s3.amazonaws.com/schedulesdirect/assets/stationLogos/s99098_h3_aa.png" width="360" />
  </channel>
`

Mike

**Comment by PBrady43** [comment]
Thanks Mike.
If there are channels in the json output which are not listed in the Mythtv database then they just will not match and be ignored in the 'commit'.   In fact, most channels (your example included) have three display-names - only one at most will match.
Regards
Phil
