### ISSUE TITLE
Database not updated when clicking on yes

### ISSUE THREAD

**Issue by MikeB2013** [PBrady43/Channel-Editor#2]
On version 2.22 (tkm04) 24 March 2018 " Database has been updated!" message is only displayed if "no" is clicked, clicking on yes does not display anything and the database is not updated. 

Looks like line 1870 has reversed operation.

Mike

**Comment by PBrady43** [comment]
Hi Mike,

Sorry for lack of reply - it's been a hectic week.

Thanks for the report - will look at it.

Phil



________________________________

**Comment by PBrady43** [comment]
Thanks Mike.  Version 2.23 12 April 2018 fixes this.
